# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a6694806c7cddce8ecb092c5a1e52a0279168f3bf52c78ec2fabb60b61a074c1aec3acc71839e08810d8f773e025ab67f264211f815fe7857635c82509684ab

test:
  secret_key_base: 9f413555420de4080d4dce6145bda69eb8f96b65cc840f2cd462aaf29867f9eba4a9354c8f2d11b747ac3bfa1582a7f085bed9b1eae6b6bff44dd402125d7b4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
